name: tiny-mlperf-env
channels:
  - conda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.5.18.1=ha878542_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgomp=12.1.0=h8d9b700_16
  - libnsl=2.0.0=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.11=h166bdaf_1014
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.3=h166bdaf_0
  - pip=22.1.1=pyhd8ed1ab_0
  - python=3.8.13=ha86cf86_0_cpython
  - python_abi=3.8=2_cp38
  - readline=8.1=h46c0cb4_0
  - setuptools=62.3.2=py38h578d9bd_0
  - sqlite=3.38.5=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - pip:
    - git+https://github.com/google/qkeras#egg=qkeras
    - git+https://github.com/kentaroy47/keras-Opcounter
    - absl-py==1.0.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - blessings==1.7
    - certifi==2022.5.18.1
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dm-tree==0.1.7
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - gpustat==0.6.0
    - hls4ml==0.6.0
    - idna==3.3
    - importlib-metadata==4.11.4
    - importlib-resources==5.7.1
    - ipykernel==6.13.0
    - ipython==8.3.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.5.1
    - jupyter==1.0.0
    - jupyter-client==7.3.1
    - jupyter-console==6.4.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - keras==2.9.0
    - keras-flops==0.1.2
    - keras-tuner==1.1.2
    - kerop==0.1.4-2205252327
    - kt-legacy==1.0.4
    - libclang==14.0.1
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mplhep==0.3.24
    - mplhep-data==0.0.3
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.8.2
    - notebook==6.4.11
    - numpy==1.22.4
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.2.0
    - onnx==1.11.0
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parse==1.6.5
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pydigitalwavetools==1.1
    - pydot==1.4.2
    - pygments==2.12.0
    - pyparser==1.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-graphviz==0.20
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==23.0.0
    - qkeras==0.9.0
    - qtconsole==5.3.0
    - qtpy==2.1.0
    - requests==2.27.1
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - seaborn==0.11.2
    - send2trash==1.8.0
    - setgpu==0.0.7
    - six==1.16.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - tensorboard==2.9.0
    - tensorflow==2.9.0
    - tensorflow-estimator==2.9.0
    - tensorflow-model-optimization==0.7.2
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.2.1.post0
    - uhi==0.3.1
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - zipp==3.8.0
prefix: /home/bhawks/.conda/envs/tiny-mlperf-env
